name: Test Jetski App
run-name: ${{ github.actor }} is testing Jetski!
on: [push]
jobs:
  Test-Jetski-App:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out repository code
        uses: actions/checkout@v5
      - run: echo "The github repo has been cloned"
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
      - run: echo "Running tests on jetski app now!"
      - run: cd jetski-app && bundle install && bundle exec ruby test_app.rb